language: go
dist: trusty
go_import_path: github.com/bookingcom/carbonapi

sudo: required

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install libcairo2-dev -y

script: make all check vet

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  include:
    - go: 1.12.x
